pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'Java!7'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/3Pratyush/Milestone4.git'
            }
        }

        stage('Workspace Check') {
            steps {
                bat 'dir'
                bat 'dir /s pom.xml'
            }
        }

        stage('Verify Tools') {
            steps {
                bat 'java -version'
                bat 'mvn -version'
            }
        }

    }
}