pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'Java!7'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/3Pratyush/Milestone4.git'
            }
        }

        stage('Verify Tools') {
            steps {
                bat 'java -version'
                bat 'mvn -version'
            }
        }

        stage('Clean') {
    steps {
        dir('Milestone4') {
            bat 'mvn clean'
        }
    }
}

stage('Test') {
    steps {
        dir('Milestone4') {
            bat 'mvn test'
        }
    }
}
}